server.port: 8080
spring.application.name: bug-wars-ui

# This is zuul configuration.
# For a good description of Zuul in general: https://howtodoinjava.com/spring-cloud/spring-cloud-api-gateway-zuul/
# For a good reference manual for application.yml: https://cloud.spring.io/spring-cloud-netflix/multi/multi__router_and_filter_zuul.html
zuul:
  host:
    # Wait 5000 seconds for timeout - Heroku needs time to spin up services on startup.
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  # Service will be mapped under the /api URI
  # By default it is stripped
  prefix: /api
  routes:
    # This is the capture point:  host + /api + /ai + /rest/Of/Path
    ai:
      # Redirected to: bug-wars-ai-crud + /ai/**  where  ** = /rest/Of/Path
      path: /**
      serviceId: bug-wars-ai-crud

---
spring.profiles: cloud
eureka:
  password: password
  instance:
    hostname: bug-wars-eureka.herokuapp.com
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:${eureka.password}@${eureka.instance.hostname}/eureka/


  # you call POST localhost:8080/api/ai/**
  # it gets redirect to:
  # localhost:8082/ai/**
---
spring.profiles: local, default
eureka:
  password: password
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:${eureka.password}@${eureka.instance.hostname}:8761/eureka/


