# This is a basic workflow to help you get started with Actions

name: Deploy Zuul Gateway / UI to Heroku

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2        
      
      - name: Cache Node Files
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-        
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        
      - name: Build and Test Angular Project
        run: |
          cd ui
          npm install
          npm build --prod
          cd ..
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2  
      
      - name: Build Spring Boot project with Maven
        run: mvn -B package --file pom.xml
         
      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bug-wars"
          heroku_email: "jerry.codecamp@gmail.com"
          justlogin: true
      
      - name: Deploy to Heroku
        run: |
          heroku plugins:install java
          heroku deploy:jar target/bug-wars-ui-0.0.1-SNAPSHOT.jar --app bug-wars
